<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title><?php echo $this->data['title'];?>  3D movie shop</title>

		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="/css/main.css">

	</head>

	<body>

		<header>
			<div class="container">
				<nav id="nav-main" class="navbar navbar-inverse navbar-fixed-top">
					<div class="container">
						<div class="navbar-header">
							<button class="navbar-toggle" data-toggle="collapse" data-target=".target">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<a class="navbar-brand active" href="/">HOME</a>
						</div>

						<div class="collapse navbar-collapse target">
							<ul class="nav navbar-nav">
								<li class=""><a href="/about">About</a></li>
								<li class=""><a href="/blog">Blog</a></li>
								<li class=""><a href="/contact">Contact</a></li>
								<?php if(isset($this->data['userType']) && $this->data['userType'] != ''){ ?>
									<li class=""><a href="/logout">Logout</a></li>
									<?php if($this->data['userType'] == 'admin') { ?>
										<li class=""><a href="/administrator">Administrator</a></li>
									<?php } ?>
								<?php } else { ?>
									<li class=""><a href="/doLogin">Login</a></li>
									<li class=""><a href="/backdoor">Backdoor</a></li>
								<?php } ?>
								<li class="">
									<form class="navbar-form" method="GET" action="/search">
										<div class="form-group">
											<input id="search" type="text" placeholder="Search"
												class="form-control" autocomplete="off"
												name="keywords" />
										</div>
										<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
									</form>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</div>
		</header>

		<main class="container">
