<?php include '_header.phtml'; ?>

<section id="about" class="container">

	<h2>About this page</h2>

	<article>
		<h3><em>Dummy</em> Purpose</h3>
		<p>We sell 3D DVD/BD.</p>
	</article>

	<article>
		<h3><em>Real</em> Purpose</h3>
		<p>I made this web site to apply my web application skills to creating EC site using HTML5, CSS, PHP, SQLite, bootstrap, Slim Framework, as well as system analysys and design technique.</p>
	</article>

	<article>
		<h3>Credit</h3>
		<p>The materials and information used in this site is retrieved from the following sites.</p>
		<ul>
			<li>http://www.amazon.ca/
			<li>http://www.imdb.com/
		</ul>
	</article>

	<article>
		<h3>Requirements</h3>
		<figure>
			<figcaption>Workflow: purchase item</figcaption>
			<img src="/images/design/AD_ WF_PurchaseItem.png"/ height="400px;">
		</figure>
		<br>
		<figure>
			<figcaption>Requirements</figcaption>
			<img src="/images/design/REQ_ Requirement.png" height="500px" />
		</figure>
	</article>

	<article>
		<h3>Software Design</h3>
		<figure>
			<figcaption>Class Diagram</figcaption>
			<img src="/images/design/CD_ overall.png"/>
		</figure>
		<br>
		<figure>
			<figcaption>Communication Diagram: List Items</figcaption>
			<img src="/images/design/OD_ ShowProductsByGenre.png"/>
		</figure>
		<br>
		<figure>
			<figcaption>Communication Diagram: Post Review</figcaption>
			<img src="/images/design/OD_ PostReview.png"/>
		</figure>
	</article>

	<article>
		<h3>DB design</h3>
		<figure>
			<figcaption>Products DB</figcaption>
			<img src="/images/design/ER_ products.png"/>
		</figure>
		<br>
		<figure>
			<figcaption>Blog DB</figcaption>
			<img src="/images/design/ER_ blog.png"/>
		</figure>
	</article>

</section>

<?php include '_footer.phtml'; ?>

