<?php include '_header.phtml'; ?>


<!-- cart info. comes here -->
<section id="cart-information" class="container">
	<h2>Cart items</h2>
	<table class="table table-bordered">
		<thead>
			<tr class="success">
				<th>PRODUCT</th>
				<th>PRICE</th>
				<th>QTY</th>
				<th>SUB TOTAL</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->data['cart'] as $item) { ?>
			<tr class="active">
				<td><?php echo $item['name']; ?></td>
				<td>$ <?php echo $item['price']; ?></td>
				<td><?php echo $item['num']; ?></td>
				<td>$ <?php echo $item['subTotal']; ?></td>
			</tr>
			<?php } ?>
		</tbody>
		<tfoot>
			<tr class="success">
				<th colspan="3">TOTAL PAYMENT</th>
				<td>$ <?php echo $this->data['total']; ?></td>
			</tr>
		</tfoot>
	</table>
</section>

<section id="customer-information" class="container">
	<h2>Order</h2>
	
	<form class="form-horizontal" method="POST" action="/order">
		<div class="form-group">
			<label for="order_name" class="col-sm-2 control-label">Name</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" name="order_name" id="order_name" placeholder="FirstName LastName">
			</div>
		</div>
		<div class="form-group">
			<label for="order_address" class="col-sm-2 control-label">Address</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" name="order_address" id="order_address" placeholder="Address">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Credit Card</label>
			<div class="col-sm-10">
				<div class="radio">
					<label>
						<input type="radio" name="order_credit_type" id="order_credit_type_visa" value="credit_type_visa" checked> VISA
					</label>
					<label>
						<input type="radio" name="order_credit_type" id="order_credit_type_master" value="credit_type_master"> MasterCard
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="order_credit_number" class="col-sm-2 control-label">Card Number</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" name="order_credit_number" id="order_credit_number">
			</div>
		</div>
		<br>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><strong>Order</strong></button>
			</div>
		</div>
	</form>


</section>

<?php include '_footer.phtml'; ?>
