<?php include '_header.phtml'; ?>

<section id="contact" class="container">
	<h2>Contact</h2>

	<div class="row">
		<div class="col-sm-8">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1592.8319442000673!2d-80.4043476026372!3d43.38930164041688!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f100!3m3!1m2!1s0x0000000000000000%3A0x2043c24369ede07e!2sConestoga+College!5e0!3m2!1sen!2sca!4v1447812919091" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>

		<div class="col-sm-4">
			<h3>How can we help you?</h3>
			<p>Sorry, I would never check your message...</p>
			<form method="post" action="/mail">
				<input type="email" name="contact_email" placeholder="Reply email address"/>
				<br />
				<input type="text" name="contact_subject" placeholder="Subject of your inquiry" />
				<br />
				<textarea name="contact_message" rows="4" placeholder="Your Inquiry"></textarea>
				<br />
				<button type="submit" class="btn btn-primary btn-md">Send</button>
				<button type="reset" class="btn btn-primary btn-md">Reset</button>
				<br />
			</form>

			<?php
			if($this->data['msg'] != '') {
				echo'
				<div class="alert alert-success" role="alert">
					<a href="#" class="alert-link">' . $this->data["msg"] . '</a>
				</div>
				';
			}
			?>

		</div>
	</div>

</section>


<?php include '_footer.phtml'; ?>

