<?php include '_header.phtml'; ?>

<!-- shop name goes here -->
<h1 id="shop-title"><span class="red">3D</span><span class="green"> Movie Shop</span></h1>

<!-- Featured products comes here -->
<section class="container hidden-xs">
	<h2>Weekly special</h2>
	<div id="slideshow">
		<div id="carousel-featured" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<?php
					$nIndex = 0;
					foreach($this->data['featuredProducts'] as $product) {
						if($nIndex % 3 == 0 && $nIndex != 0) {
							echo '<div class="item">';
						}
						echo '
							<div class="col-sm-4">
								<a href="/product/' . $product->productId . '">
								<img src="' . $product->image . '" alt="' . $product->name . '" title="' . $product->name . '" height=300px></a>
							</div>';
						if(($nIndex+1) % 3 == 0) {
							echo '</div>';
						}
						$nIndex++;
					}
					if($nIndex % 3 != 0) {
						echo '</div>';
					}
					?>
				<a class="left carousel-control" href="#carousel-featured" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-featured" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>
</section>

<!-- products categorized by genre-tab comes here -->
<section class="container">
	<h2>Our products</h2>
	<!-- create tabs for each genre -->
	<ul id="list-genre" class="nav nav-tabs">
		<?php
		foreach($this->data['genreAll'] as $genre) {
			if($genre->name == $this->data['genreSelected'] ){
				echo '<li role="presentation" class="active"><a href="#"><strong>' . $genre->name . '</strong></a></li>';
			} else {
				echo '<li role="presentation"><a href="/home/' . $genre->name . '"><strong>' . $genre->name . '</strong></a></li>';
			}
		}
		?>
	</ul>

	<!-- show all products of selected genre -->
	<div id="products-genre" class="container">
		<?php
		foreach($this->data['productsInGenre'] as $product) {
			echo '<article class="product-listed">';
			echo '<h3 class="title"><a href="/product/' . $product->id . '">' . $product->name . '</a></h3>';
			echo '
				<div class="row">
					<div class="col-xs-3">
						<a href="/product/' . $product->id . '">
							<img class="jacket" src="' . $product->image . '" width = 100% alt="' . $product->name . '" title="' . $product->name . '">
						</a>
					</div>
					<div class="col-xs-9">
						<p class="description">' . $product->description . '</p>
						<p class="date">' . $product->date . '</p>
					</div>
				</div>
			</article>
			';
		}
		?>
	</div>
</section>


<?php include '_footer.phtml'; ?>
