<?php include '_header.phtml'; ?>


<!-- Selected product info. comes here -->
<section id="product-information" class="container">
	<?php
	$product = $this->data['product'];
	echo '<h2>' . $product->name . '</h2>';
	?>
	<div class="row">
		<div class="col-xs-8">
			<div class="row">
				<div class="col-xs-6">
					<img src=" <?php echo $product->image ?>" width = 100% alt="<?php echo $product->name; ?>" title="<?php echo  $product->name; ?>">
				</div>
				<div class="col-xs-6">
					<dl>
						<dt>Price</dt>
						<dd>$<?php echo $product->price; ?></dd>
						<dt>Date</dt>
						<dd><?php echo $product->date; ?></dd>
					</dl>
					<?php if($product->stockQuantity == 0){ ?>
					<div class="alert alert-danger" role="alert">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span class="sr-only">Out of Order:</span>
						Sorry. This item is currently out of order.
					</div>
					<?php } ?>
				</div>
			</div>
			<br>
			<dl>
				<dt>Description</dt>
				<dd><?php echo $product->description; ?></dd>
				<dt>Actors</dt>
				<dd><?php echo $product->starring; ?></dd>
			</dl>
		</div>

		<div class="col-xs-4">
			<form method="POST" action="/addCart">
				<input type="hidden" name="productId" value="<?php echo $product->id; ?>">
				<button type="submit" class="btn btn-primary">Add to cart</button>
			</form>
			<p>
				<?php echo $this->data['numInCart']; ?>  items in your cart
			</p>
			<a href="/cart" class="btn btn-primary">Go to Cart</a>
		</div>
	</div>
</section>

<section id="reviews" class="container">
	<h2>Reviews</h2>
	<!-- posted reviews comes here -->
	<?php
	foreach($this->data['reviews'] as $review) {
		echo '<article class="product-review">';
		echo '<p>';
		for($i = 0; $i < $review->rate; $i++){
			echo '<span class="glyphicon glyphicon-star yellow"></span>';
		}
		for($i = 0; $i < 5 - $review->rate; $i++){
			echo '<span class="glyphicon glyphicon-star-empty"></span>';
		}
		//echo ' (' . $review->rate . ')';
		echo '</p>';

		echo '<p>' . $review->comment . '</p>';
		echo '<p>by ' . $review->writer . ' ( ' . $review->date . ' )</p>';
		echo '</article>';
	}
	if(count($this->data["reviews"]) == 0){
		echo 'No reviews so far...';
	}
	?>

	<!-- post review form comes here -->
	<h3>Review this movie</h3>
	<form id="post-review" class="form-horizontal" method="POST" action="/product/<?php echo $product->id; ?>">
		<div class="form-group">
			<label for="review_star" class="col-sm-2 control-label">Star</label>
			<div class="col-sm-10">
				<select class="form-control" id="review_star" name="review_star" >
					<option>1</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="review_comment" class="col-sm-2 control-label">Comment</label>
			<div class="col-sm-10">
				<textarea class="form-control" id="review_comment" name="review_comment" rows="3" placeholder="Comment"></textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="review_writer" class="col-sm-2 control-label">Name</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" id="review_writer" name="review_writer" placeholder="Name">
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-success">Post Review</button>
			</div>
		</div>
	</form>
</section>

<!-- Related products comes here -->
<section class="container">
	<h2>Related Products</h2>
	<div id="slideshow">
		<div id="carousel-related" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<?php
					$nIndex = 0;
					foreach($this->data['relatedProducts'] as $relatedProduct) {
						if($nIndex % 3 == 0 && $nIndex != 0) {
							echo '<div class="item">';
						}
						echo '
							<div class="col-xs-4">
								<a href="/product/' . $relatedProduct->id . '">
								<img src="' . $relatedProduct->image . '"  alt="' . $relatedProduct->name . '" title="' . $relatedProduct->name . '" height=300px></a>
							</div>';
						if(($nIndex+1) % 3 == 0) {
							echo '</div>';
						}
						$nIndex++;
					}
					if($nIndex % 3 != 0) {
						echo '</div>';
					}
					?>
				<a class="left carousel-control" href="#carousel-related" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-related" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>
</section>


<?php include '_footer.phtml'; ?>
